name: 🐧 Linux Builds
on: [push, pull_request]

# Global Settings
env:
  DOTNET_NOLOGO: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  EM_VERSION: 3.1.18
  EM_CACHE_FOLDER: "emsdk-cache"

concurrency:
  group: ci-${{github.actor}}-${{github.head_ref || github.run_number}}-${{github.ref}}-deploy
  cancel-in-progress: true

jobs:
  build-linux:
    runs-on: "ubuntu-20.04"
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - id: godot
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          repository: V-Sekai/godot
          excludes: prerelease, draft

      - name: Download Linux Editor Mono
        run: |
          wget "https://github.com/V-Sekai/godot/releases/download/${{ steps.godot.outputs.release }}/linux-editor-mono.zip"

      - name: Download Windows Editor
        run: |
          wget "https://github.com/V-Sekai/godot/releases/download/${{ steps.godot.outputs.release }}/windows-editor.zip"

      - name: Unzip Windows Editor
        run: |
          unzip windows-editor.zip -d godot-windows-editor

      - name: Unzip Linux Editor Mono
        run: |
          unzip linux-editor-mono.zip -d godot-linux-editor

      - name: Export Game
        run: |
          mkdir -p .godot/editor .godot/imported export_linux
          chmod +x godot-linux-editor/linux-editor-mono/godot.linuxbsd.editor.x86_64.mono  
          godot-linux-editor/linux-editor-mono/godot.linuxbsd.editor.x86_64.mono --headless --xr-mode off --export-pack Linux  `pwd`/v_sekai_game_windows_x64.pck --path .

      - name: Export Game for Linux
        run: |
          mkdir -p .godot/editor .godot/imported export_linux
          chmod +x godot-linux-editor/linux-editor-mono/godot.linuxbsd.editor.x86_64.mono  
          godot-linux-editor/linux-editor-mono/godot.linuxbsd.editor.x86_64.mono --headless --xr-mode off --export-pack Linux `pwd`/v_sekai_game_linux_x64.pck --path .
      
      - name: Prepare Linux artifacts
        run: |
          rm -rf v_sekai_game_linux_x64
          export TARGET=v_sekai_game_linux_x64
          mkdir -p $TARGET
          cp -rf godot-linux-editor/linux-editor-mono/godot.linuxbsd.editor.x86_64.mono $TARGET/v_sekai_game_linux_x64.mono
          cp -rf v_sekai_game_linux_x64.pck $TARGET/v_sekai_game_linux_x64.pck
          7z a -r $TARGET.zip $TARGET
        shell: bash

      - name: Upload Godot Artifact Export for Linux
        uses: actions/upload-artifact@v3
        with:
          name: v_sekai_game_linux_x64
          path: |
            v_sekai_game_linux_x64/v_sekai_game_linux_x64.mono
            v_sekai_game_linux_x64/v_sekai_game_linux_x64.pck

      - name: Prepare Windows artifacts
        run: |
          rm -rf v_sekai_game_windows_x64
          export TARGET=v_sekai_game_windows_x64
          mkdir -p $TARGET
          cp -rf  godot-windows-editor/windows-editor/godot.windows.editor.x86_64.exe $TARGET/v_sekai_game_windows_x64.exe
          cp -rf v_sekai_game_windows_x64.pck $TARGET/v_sekai_game_windows_x64.pck
          7z a -r $TARGET.zip $TARGET
        shell: bash

      - name: Upload Godot Artifact Export for Windows
        uses: actions/upload-artifact@v3
        with:
          name: v_sekai_game_windows_x64
          path: |
            v_sekai_game_windows_x64/v_sekai_game_windows_x64.exe
            v_sekai_game_windows_x64/v_sekai_game_windows_x64.pck

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            v_sekai_game_linux_x64/v_sekai_game_linux_x64.mono
            v_sekai_game_linux_x64/v_sekai_game_linux_x64.pck
            v_sekai_game_windows_x64/v_sekai_game_windows_x64.exe
            v_sekai_game_windows_x64/v_sekai_game_windows_x64.pck
          body: "This is a V-Sekai/V-Sekai-game release"
          generate_release_notes: true
          draft: true
          prerelease: true
          append_body: true
